name: n5-mc_none__y_write
on:
  workflow_dispatch:
jobs:
  c_none__y_write:
    cache-mode: none
    uses: 0xlux-dz/n5-callee/.github/workflows/callee_write.yml@main
    with: {pair_id: "${{ github.job }}"}
