name: n5-mc_write__y_inherit
on:
  workflow_dispatch:
jobs:
  c_write__y_inherit:
    cache-mode: write
    uses: 0xlux-dz/n5-callee/.github/workflows/callee_inherit.yml@main
    with: {pair_id: "${{ github.job }}"}
