name: n5-mc_read__y_inherit
on:
  workflow_dispatch:
jobs:
  c_read__y_inherit:
    cache-mode: read
    uses: 0xlux-dz/n5-callee/.github/workflows/callee_inherit.yml@main
    with: {pair_id: "${{ github.job }}"}
